### ISSUE TITLE
Your code does not run

### ISSUE THREAD

**Issue by AssafMashiah** [lobrown/Full-Stack-Foundations#21]
Final project has syntax errors and is not PEP8

**Comment by AssafMashiah** [comment]
Well I am sorry for been rude... there where some explanations in the Udacity site and no people on the forum.... :(
I took your curse and it was fun! 
I made some changes and made it PEP8 compatible. Can I contribute to the code?

**Comment by scheung38** [comment]
After git clone and trying to run:

Lesson-3/02_Adding-Database-to-Flask-Application/project.py

from database_setup import Base, Restaurant, MenuItem cannot be resolved?

Could you please tell me how to run when imports are not resolved?

**Comment by luhar88** [comment]
@scheung38 - If imports are not resolved then you won't be able to run the application. Do you have the database_setup.py file in your flask application folder?

**Comment by scheung38** [comment]
After git clone into my working directory:

```python
/User/seb/PycharmProjects/Full_Stack_Foundations
```

**Comment by lobrown** [comment]
Thank you, @AssafMashiah,  I apologize for the solution code issues in this course, I was in the process of making another course but I will test all of the solution code and make it PEP8 compliant as very soon! Feel free to do a pull request if you believe you have some improvements to the code as well.  The forums had some spamming issues but I believe they are up and running now for students inside and outside of the Nanodegree.

**Comment by lobrown** [comment]
@scheung38 the database for this course is an sqlite file. Try moving this file into your working directory and then ```engine = create_engine('sqlite:///restaurants.db')```
