### ISSUE TITLE
Errors in Final-Flask-Application

### ISSUE THREAD

**Issue by cacrookes** [lobrown/Full-Stack-Foundations#24]
Hi, I noticed some errors in the final code.

In project.py:
* line 59, when editing a menu item you have the item description being set to the the item name.
* line 81, you try to render deleteconfirmation.html, which doesn't exist. This should be deletemenuitem.html, or else deletemenuitem.html needs to be renamed

In deletemenuitem.html
* line 17, you pass 'showMenu' into url_for. 'showMenu' is not defined. This should be restaurantMenu

In editmenuitem.html
* line 57, you pass 'showRestaurants' into url_for. 'showRestaurants' is not defined. This should be restaurantMenu

**Comment by lobrown** [comment]
Thanks for pointing these out @cacrookes , and my apologies for such a delayed response.  I had to jump on another course, but now I am spending time addressing all of the issues with Full Stack Foundations.  I will add this to my list of improvements and please feel free to drop me a line if you see any other bugs.  You can also do a pull request and I will merge your changes.  Cheers! --Lorenzo

**Comment by guillermogfer** [comment]
Hi,
I've included this points in a pull request along with others minor changes.
