### ISSUE TITLE
Lesson-3/11_form-requests-and-redirects/project.py line 28 clarification

### ISSUE THREAD

**Issue by notesofdabbler** [lobrown/Full-Stack-Foundations#3]
Just wanted to check on line 28 in the code:
Lesson-3/11_form-requests-and-redirects/project.py

line 28:   	return redirect(url_for('restaurantMenu', restaurant_id = restaurant_id))

should it be 'HelloWorld' instead of 'restaurantMenu'?

Thanks,

**Comment by lobrown** [comment]
Hi @notesofdabbler  Since the HelloWorld(restaurant_id) didn't make much since. I changed it to restaurantMenu(restaurant_id).  I will be sure to make a about comment this in the instructor notes in the classroom.

Cheers,
Lorenzo
