### ISSUE TITLE
/Lesson-3/14_Delete-Menu-Item/deletemenuitem.html (line 15 clarification)

### ISSUE THREAD

**Issue by notesofdabbler** [lobrown/Full-Stack-Foundations#4]
/Lesson-3/14_Delete-Menu-Item/deletemenuitem.html has the following syntax (line 15):
href = "url_for{{('restaurantMenu', restaurant_id = restaurant_id')}}"> Cancel 

The above code gave a error but the following change in syntax worked (moving the curly braces):
href = "{{url_for('restaurantMenu', restaurant_id = restaurant_id')}}"> Cancel

**Comment by lobrown** [comment]
Sorry about that @notesofdabbler this should be fixed on the repository now.
